# Generated by Django 5.2.6 on 2025-09-24 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_activities', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(error_messages={'blank': 'La description ne peut pas être vide.'}, validators=[django.core.validators.MinLengthValidator(10, 'La description doit contenir au moins 10 caractères.')], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(error_messages={'blank': "La date et l'heure de fin ne peuvent pas être vides.", 'null': "La date et l'heure de fin sont requises."}, verbose_name='Date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location_city',
            field=models.CharField(error_messages={'blank': 'La ville ne peut pas être vide.', 'max_length': 'La ville ne peut pas dépasser 100 caractères.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'La ville doit contenir au moins 2 caractères.')], verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(error_messages={'blank': "La date et l'heure de début ne peuvent pas être vides.", 'null': "La date et l'heure de début sont requises."}, verbose_name='Date et heure de début'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(error_messages={'blank': 'Le titre ne peut pas être vide.'}, validators=[django.core.validators.MinLengthValidator(5, 'Le titre doit contenir au moins 5 caractères.'), django.core.validators.MaxLengthValidator(200, 'Le titre doit contenir au plus 200 caractères.')], verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'blank': 'Le nom de la catégorie ne peut pas être vide.', 'max_length': 'Le nom de la catégorie ne peut pas dépasser 100 caractères.', 'unique': 'Une catégorie avec ce nom existe déjà.'}, max_length=100, unique=True, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biographie'),
        ),
    ]
