# Generated by Django 5.2.6 on 2025-09-26 20:35

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_user_options_alter_activity_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(error_messages={'required': "La date et l'heure de fin sont requises."}, verbose_name='Date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(error_messages={'required': "La date et l'heure de début sont requises."}, verbose_name='Date et heure de début'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Téléchargez une image pour votre avatar (JPG, PNG, GIF ou WebP - 2MB max)', null=True, upload_to=activities.models.avatar_upload_path, validators=[activities.models.validate_avatar_extension, activities.models.validate_avatar_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Parlez-nous un peu de vous (optionnel).', max_length=500, null=True, verbose_name='Biographie'),
        ),
    ]
